---
- title: Plastering/ Gyprocking / Interior Lining /  Partitioning
  description: "we offer Dry Plastering, Suspended ceiling with plasterboard or any
    other materials. room Partitioning, wall, ceiling and floor covering. \n\nso if
    you need more space or more rooms, please contact us!"
- title: Painting and decorating
  description: "Family members are painters as advantage for us to take on gyprock
    and painting at most of the jobs. Less complaints between final finish with 2
    trades. we got you sorted. \n"
- title: Extensions and Refurbishments
  description: |
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ac posuere neque, a ullamcorper orci. Sed sit amet ullamcorper tortor. Etiam ut enim ante. Phasellus sed condimentum est. Duis tincidunt, dolor a semper egestas, libero erat laoreet turpis, quis viverra leo ex sit amet lectus. Donec vitae dolor nunc. In sit amet turpis turpis. Aliquam eget elit at ligula convallis viverra sed quis metus. Curabitur id ornare nunc.
- title: Land and Building Packages
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ac posuere
    neque, a ullamcorper orci. Sed sit amet ullamcorper tortor. Etiam ut enim ante.
    Phasellus sed condimentum est. Duis tincidunt, dolor a semper egestas, libero
    erat laoreet turpis, quis viverra leo ex sit amet lectus. Donec vitae dolor nunc.
    In sit amet turpis turpis. Aliquam eget elit at ligula convallis viverra sed quis
    metus. Curabitur id ornare nunc.
