---
- title: Plastering/ Gyprocking / Interior Lining /  Partitioning
  description: "we offer Dry Plastering, Suspended ceiling with plasterboard or any
    other materials. room Partitioning, wall, ceiling and floor covering. \n\nso if
    you need more space or more rooms, please contact us!"
- title: Painting and decorating
  description: "Family members are painters as advantage for us to take on gyprock
    and painting at most of the jobs. Less complaints between final finish with 2
    trades. we got you sorted. \n"
- title: commerical glazing partitions
  description: Glazing partitions in offices and shops. Residential works welcome
- title: ''
  description: ''
